testname: Minimal Test
testId: minimal_test
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
showConditionNames: false
pages:
  - type: mushra
    id: trial1
    name: Test Trial
    reference: audio/ref/te1_mg54_speech.m4a
    stimuli:
      dac: audio/dac/te1_mg54_speech_dac_full.m4a
  - type: finish
    name: Thank you
    content: Done
    showResults: true
    writeResults: false