# test config mushra page, 2 trials: 1) not randomized, condition names shown 2) 

testname: MUSHRA EBNAC
testId: mushra_ebnac_24
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:

    # - type: mushra
    #   id: trial0
    #   name: Mono Trial
    #   content: test description
    #   showWaveform: true
    #   enableLooping: true
    #   reference: /home/bhkim98/webMUSHRA/audio/ref/AAA.wav
    #   createAnchor35: true
    #   createAnchor70: false
    #   randomize: false
    #   showConditionNames: true
    #   stimuli:
    #       C1: /home/bhkim98/webMUSHRA/audio/mp3/AAA_mp3.wav
    #       C2: /home/bhkim98/webMUSHRA/audio/aaclc/AAA_aac.wav
    #       C3: /home/bhkim98/webMUSHRA/audio/heaacv1/AAA_aac.wav
    #       C4: /home/bhkim98/webMUSHRA/audio/dac/AAA_dac_full.wav
    #       C5: /home/bhkim98/webMUSHRA/audio/heaacv1/AAA_aac.wav
    #       C6: /home/bhkim98/webMUSHRA/audio/sauber/gd_max30_lr0p08_cfg2.0_dcoff_encc32_deccoff_encw4_msc32_ninilinear_nit1p5/AAA_i200000.wav
          

    - type: mushra
      id: trial1
      name: Mono Trial
      content: test description
      showWaveform: true
      enableLooping: true
      reference: /home/bhkim98/webMUSHRA/audio/ref/HarryPotter.wav
      createAnchor35: true
      createAnchor70: false
      randomize: false
      showConditionNames: true
      stimuli:
          C1: /home/bhkim98/webMUSHRA/audio/mp3/HarryPotter_mp3.wav
          C2: /home/bhkim98/webMUSHRA/audio/aaclc/HarryPotter_aac.wav
          C3: /home/bhkim98/webMUSHRA/audio/heaacv1/HarryPotter_aac.wav
          C4: /home/bhkim98/webMUSHRA/audio/dac/HarryPotter_dac_full.wav
          C5: /home/bhkim98/webMUSHRA/audio/heaacv1/HarryPotter_aac.wav
          C6: /home/bhkim98/webMUSHRA/audio/sauber/gd_max30_lr0p08_cfg2.0_dcoff_encc32_deccoff_encw4_msc32_ninilinear_nit1p5/HarryPotter_i200000.wav
    
    - type: mushra
      id: trial2
      name: Mono Trial
      content: test description
      showWaveform: true
      enableLooping: true
      reference: /home/bhkim98/webMUSHRA/audio/ref/te15.wav
      createAnchor35: true
      createAnchor70: false
      randomize: false
      showConditionNames: true
      stimuli:
          C1: /home/bhkim98/webMUSHRA/audio/mp3/te15_mp3.wav
          C2: /home/bhkim98/webMUSHRA/audio/aaclc/te15_aac.wav
          C3: /home/bhkim98/webMUSHRA/audio/heaacv1/te15_aac.wav
          C4: /home/bhkim98/webMUSHRA/audio/dac/te15_dac_full.wav
          C5: /home/bhkim98/webMUSHRA/audio/heaacv1/te15_aac.wav
          C6: /home/bhkim98/webMUSHRA/audio/sauber/gd_max30_lr0p08_cfg2.0_dcoff_encc32_deccoff_encw4_msc32_ninilinear_nit1p5/te15_i200000.wav


    - type: finish
      name: Thank you
      content: Thank you for attending
      popupContent: Your results were sent. Goodbye and have a nice day      
      showResults: true
      writeResults: true
